# Generated by Django 5.0.7 on 2024-08-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_is_2fa_enabled_customuser_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_speaking_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
