# Generated by Django 5.0.7 on 2024-08-10 17:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('nutritional_info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NutritionDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('nutrition_data', models.JSONField()),
                ('source', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('recognized_food', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('week_start', models.IntegerField()),
                ('week_end', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['week_start', 'week_end'], name='vision_preg_week_st_780ff6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPregnancyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('current_weight', models.FloatField()),
                ('height', models.FloatField()),
                ('pre_pregnancy_weight', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.FloatField(default=0.5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('portion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='vision_food_user_id_707a52_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('pregnancy_week', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['food', 'pregnancy_week'], name='vision_food_food_id_fee7db_idx')],
                'unique_together': {('user', 'food')},
            },
        ),
        migrations.CreateModel(
            name='FoodRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date', models.DateField(db_index=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='vision_food_user_id_d70667_idx')],
            },
        ),
        migrations.CreateModel(
            name='NutrientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(db_index=True, max_length=100)),
                ('daily_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('pregnancy_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.pregnancystage')),
            ],
            options={
                'indexes': [models.Index(fields=['pregnancy_stage', 'nutrient_name'], name='vision_nutr_pregnan_c6318c_idx')],
            },
        ),
    ]
